spring:
  application:
    name: paymentProcessor
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: tech
    password: test
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka-server:9292,localhost:29092
server:
  port: 8080
global:
  validatePaymentEndpoint: http://localhost:9000/payment