spring:
  application:
    name: paymentProcessor
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: tech
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080